
console.log('----\n')
console.log(`4 + 4 = ${4 + 4}\n`)
console.log('----\n')
console.log(`20 - 12 = ${20 - 12}\n`)
console.log('----\n')
console.log(`02 * 04 = ${2 * 4}\n`)
console.log('----\n')
console.log(`32 / 4 = ${32 / 4}\n`)
console.log('----\n')